name: risaal_crypto
description: Military-grade Signal Protocol implementation in pure Dart. Includes X3DH, Double Ratchet, Sealed Sender, Sender Keys, Kyber-768 post-quantum hybrid, and LSB steganography.
version: 0.2.1
homepage: https://github.com/AnonDevBoss/risaal-crypto

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.5
  cryptography: ^2.7.0
  pqcrypto: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
